package com.example.demo.wsdl_client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2024-01-26T08:57:30.445Z
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "ClientWSService",
                  wsdlLocation = "http://10.10.0.16/signserver/ClientWSService/ClientWS?wsdl",
                  targetNamespace = "http://clientws.signserver.org/")
public class ClientWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://clientws.signserver.org/", "ClientWSService");
    public final static QName ClientWSPort = new QName("http://clientws.signserver.org/", "ClientWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.10.0.16/signserver/ClientWSService/ClientWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClientWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.10.0.16/signserver/ClientWSService/ClientWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClientWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClientWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ClientWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ClientWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ClientWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClientWS
     */
    @WebEndpoint(name = "ClientWSPort")
    public ClientWS getClientWSPort() {
        return super.getPort(ClientWSPort, ClientWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientWS
     */
    @WebEndpoint(name = "ClientWSPort")
    public ClientWS getClientWSPort(WebServiceFeature... features) {
        return super.getPort(ClientWSPort, ClientWS.class, features);
    }

}
