package com.example.demo.wsdl_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2024-01-26T08:57:30.445Z
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://clientws.signserver.org/", name = "ClientWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ClientWS {

    @WebMethod
    @RequestWrapper(localName = "processSOD", targetNamespace = "http://clientws.signserver.org/", className = "com.example.demo.wsdl_client.ProcessSOD")
    @ResponseWrapper(localName = "processSODResponse", targetNamespace = "http://clientws.signserver.org/", className = "com.example.demo.wsdl_client.ProcessSODResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.demo.wsdl_client.SodResponse processSOD(

        @WebParam(name = "worker", targetNamespace = "")
        String worker,
        @WebParam(name = "metadata", targetNamespace = "")
        java.util.List<com.example.demo.wsdl_client.Metadata> metadata,
        @WebParam(name = "sodData", targetNamespace = "")
        com.example.demo.wsdl_client.SodRequest sodData
    ) throws RequestFailedException_Exception, InternalServerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "processData", targetNamespace = "http://clientws.signserver.org/", className = "com.example.demo.wsdl_client.ProcessData")
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://clientws.signserver.org/", className = "com.example.demo.wsdl_client.ProcessDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.demo.wsdl_client.DataResponse processData(

        @WebParam(name = "worker", targetNamespace = "")
        String worker,
        @WebParam(name = "metadata", targetNamespace = "")
        java.util.List<com.example.demo.wsdl_client.Metadata> metadata,
        @WebParam(name = "data", targetNamespace = "")
        byte[] data
    ) throws RequestFailedException_Exception, InternalServerException_Exception;
}
