
package com.example.demo.wsdl_client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2024-01-26T08:57:30.414Z
 * Generated source version: 3.5.0
 */

@WebFault(name = "InternalServerException", targetNamespace = "http://clientws.signserver.org/")
public class InternalServerException_Exception extends Exception {

    private com.example.demo.wsdl_client.InternalServerException faultInfo;

    public InternalServerException_Exception() {
        super();
    }

    public InternalServerException_Exception(String message) {
        super(message);
    }

    public InternalServerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InternalServerException_Exception(String message, com.example.demo.wsdl_client.InternalServerException internalServerException) {
        super(message);
        this.faultInfo = internalServerException;
    }

    public InternalServerException_Exception(String message, com.example.demo.wsdl_client.InternalServerException internalServerException, Throwable cause) {
        super(message, cause);
        this.faultInfo = internalServerException;
    }

    public com.example.demo.wsdl_client.InternalServerException getFaultInfo() {
        return this.faultInfo;
    }
}
